'use client';
import React,{useCallback,useEffect,useState} from 'react';
export default function AnalyticsPanel({authedFetch}:{authedFetch:(path:string,init?:RequestInit)=>Promise<Response>}){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');const load=useCallback(async()=>{const r=await authedFetch('/api/admin/analytics');const p=await r.json().catch(()=>null);if(!r.ok){setError(p?.message??'Could not load analytics.');return;}setData(p.data);},[authedFetch]);useEffect(()=>{void load();},[load]);
 if(error)return <div className="border border-brand-accent/50 bg-brand-card p-4 text-xs">{error}</div>;if(!data)return <p className="text-xs text-brand-textMuted">Loading analytics...</p>;
 const max=Math.max(1,...data.daily.map((d:any)=>d.revenue));return <div className="space-y-6">
  <p className="text-xs text-brand-textMuted">Last 90 days · updated {new Date(data.generatedAt).toLocaleString()}</p>
  <div className="grid grid-cols-2 gap-px border border-brand-border bg-brand-border lg:grid-cols-6">{[['Revenue',`$${Number(data.totals.revenue).toFixed(2)}`],['Orders',data.totals.orders],['Average order',`$${Number(data.totals.averageOrder).toFixed(2)}`],['Leads',data.totals.leads],['Open carts',data.totals.abandonedCarts],['Recovered carts',data.totals.recoveredCarts]].map(([l,v])=><div key={String(l)} className="bg-brand-card p-4"><div className="eyebrow">{l}</div><div className="mt-2 font-display text-xl font-black text-brand-heading">{v}</div></div>)}</div>
  <section className="border border-brand-border bg-brand-card p-4"><h2 className="font-display text-sm font-black uppercase text-brand-heading">Daily revenue</h2><div className="mt-4 flex h-44 items-end gap-1 overflow-x-auto">{data.daily.slice(-45).map((d:any)=><div key={d.date} title={`${d.date}: $${d.revenue.toFixed(2)} · ${d.orders} orders`} className="min-w-[8px] flex-1 bg-action" style={{height:`${Math.max(3,(d.revenue/max)*100)}%`}} />)}</div></section>
  <div className="grid gap-4 lg:grid-cols-3"><Breakdown title="Order status" values={data.statuses}/><Breakdown title="Lead status" values={data.leadStatuses}/><section className="border border-brand-border bg-brand-card p-4"><h2 className="font-display text-sm font-black uppercase text-brand-heading">Lowest stock</h2><div className="mt-3 space-y-2">{data.lowStock.map((p:any)=><div key={p.id} className="flex justify-between border-t border-brand-border pt-2 text-xs"><span>{p.name}</span><strong>{p.stock_count}</strong></div>)}</div></section></div>
 </div>;
}
function Breakdown({title,values}:{title:string;values:Record<string,number>}){return <section className="border border-brand-border bg-brand-card p-4"><h2 className="font-display text-sm font-black uppercase text-brand-heading">{title}</h2><div className="mt-3 space-y-2">{Object.entries(values).map(([k,v])=><div key={k} className="flex justify-between border-t border-brand-border pt-2 text-xs capitalize"><span>{k}</span><strong>{v}</strong></div>)}</div></section>}
