'use client';
import React,{useCallback,useEffect,useState} from 'react';
import { Pencil, Plus, Trash2, X } from 'lucide-react';
type Category={id:string;name:string;slug:string;description:string;sort_order:number;is_active:boolean;product_count:number};
const blank={name:'',slug:'',description:'',sort_order:0,is_active:true};
export default function CategoriesPanel({authedFetch}:{authedFetch:(path:string,init?:RequestInit)=>Promise<Response>}){
 const [rows,setRows]=useState<Category[]>([]);const [editing,setEditing]=useState<Category|null|undefined>(undefined);const [form,setForm]=useState<any>(blank);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await authedFetch('/api/admin/categories');const p=await r.json().catch(()=>null);if(!r.ok){setError(p?.message??'Could not load categories.');return;}setRows(p.data.categories);},[authedFetch]);useEffect(()=>{void load();},[load]);
 const open=(row:Category|null)=>{setEditing(row);setForm(row?{...row}:blank);setError('');};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const r=await authedFetch('/api/admin/categories',{method:editing?'PATCH':'POST',body:JSON.stringify(editing?{id:editing.id,...form}:form)});const p=await r.json().catch(()=>null);if(!r.ok)setError(p?.message??'Could not save category.');else{setEditing(undefined);await load();}setBusy(false);};
 const remove=async(row:Category)=>{if(!window.confirm(`Delete ${row.name}? Categories containing products cannot be deleted.`))return;const r=await authedFetch(`/api/admin/categories?id=${row.id}`,{method:'DELETE'});const p=await r.json().catch(()=>null);if(!r.ok)setError(p?.message??'Could not delete category.');else await load();};
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 border border-brand-border bg-brand-card p-4"><div><p className="font-display text-sm font-black uppercase text-brand-heading">{rows.length} categories</p><p className="mt-1 text-xs text-brand-textMuted">Renaming a category moves its existing products. A category in use cannot be deleted.</p></div><button onClick={()=>open(null)} className="btn-primary"><Plus className="h-3.5 w-3.5"/>New category</button></div>{error&&<div className="border border-brand-accent/50 bg-brand-card p-3 text-xs">{error}</div>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(row=><article key={row.id} className="border border-brand-border bg-brand-card p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-xs font-black text-brand-heading">{row.name}</h2><p className="mt-1 font-mono text-[0.6875rem] text-brand-textMuted">/{row.slug}</p></div><span className={row.is_active?'text-whatsapp':'text-brand-textMuted'}>{row.is_active?'Active':'Hidden'}</span></div><p className="mt-3 line-clamp-3 text-xs leading-relaxed text-brand-textMuted">{row.description||'No description.'}</p><div className="mt-4 flex items-center border-t border-brand-border pt-3"><span className="text-xs text-brand-textMuted">{row.product_count} products · position {row.sort_order}</span><button onClick={()=>open(row)} className="ml-auto p-2 text-brand-body hover:text-brand-accentGlow"><Pencil className="h-3.5 w-3.5"/></button><button onClick={()=>void remove(row)} className="p-2 text-brand-textMuted hover:text-brand-accentGlow"><Trash2 className="h-3.5 w-3.5"/></button></div></article>)}</div>
 {editing!==undefined&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4"><form onSubmit={save} className="max-h-[calc(100dvh-2rem)] w-full max-w-lg overflow-y-auto border border-brand-border bg-brand-card p-5 [scrollbar-width:thin]"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-sm font-black uppercase text-brand-heading">{editing?'Edit category':'New category'}</h2><button type="button" onClick={()=>setEditing(undefined)}><X className="h-4 w-4"/></button></div><div className="space-y-4">{[['name','Name'],['slug','Web address'],['description','Description']].map(([key,label])=><label key={key} className="block"><span className="eyebrow mb-1 block">{label}</span>{key==='description'?<textarea rows={4} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full border border-brand-border bg-brand-dark p-3 text-xs"/>:<input required={key==='name'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full border border-brand-border bg-brand-dark p-3 text-xs"/>}</label>)}<label className="block"><span className="eyebrow mb-1 block">Sort position</span><input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})} className="w-full border border-brand-border bg-brand-dark p-3 text-xs"/></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Visible on storefront</label></div><div className="mt-5 flex gap-2"><button disabled={busy} className="btn-primary flex-1">{busy?'Saving...':'Save category'}</button><button type="button" onClick={()=>setEditing(undefined)} className="btn-ghost">Cancel</button></div></form></div>}
 </div>;
}
