'use client';
import React, { useCallback, useEffect, useState } from 'react';

type Row = { id:string; type:'affiliate'|'seller'; beneficiary:string; order_number:string; kind?:string; rate?:number; amount:number; status:string; created_at:string; reference?:string|null };
export default function CommissionsPanel({ authedFetch }:{ authedFetch:(path:string, init?:RequestInit)=>Promise<Response> }) {
  const [rows,setRows]=useState<Row[]>([]); const [totals,setTotals]=useState<any>({}); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const load=useCallback(async()=>{ setError(''); const res=await authedFetch('/api/admin/commissions/manage'); const p=await res.json().catch(()=>null); if(!res.ok){setError(p?.message??'Could not load commissions.');return;} setRows(p.data.rows);setTotals(p.data.totals); },[authedFetch]);
  useEffect(()=>{void load();},[load]);
  const change=async(row:Row,status:string)=>{ const reference=status==='paid' ? window.prompt('Payment reference (optional)') : ''; if(status==='paid'&&reference===null)return; setBusy(row.id); const res=await authedFetch('/api/admin/commissions/manage',{method:'PATCH',body:JSON.stringify({id:row.id,type:row.type,status,reference})}); const p=await res.json().catch(()=>null); if(!res.ok)setError(p?.message??'Could not update commission.'); else await load(); setBusy(''); };
  return <div className="space-y-4">
    <div className="grid grid-cols-2 gap-px border border-brand-border bg-brand-border md:grid-cols-4">{['pending','approved','paid','void'].map(s=><div key={s} className="bg-brand-card p-4"><div className="eyebrow">{s}</div><div className="mt-2 font-display text-xl font-black text-brand-heading">${Number(totals[s]??0).toFixed(2)}</div></div>)}</div>
    {error&&<div className="border border-brand-accent/50 bg-brand-card p-3 text-xs">{error}</div>}
    <div className="overflow-x-auto border border-brand-border"><table className="w-full min-w-[52rem] text-left text-xs"><thead className="bg-brand-card"><tr>{['Person','Source','Order','Rate','Amount','Status','Created','Actions'].map(h=><th key={h} className="px-3 py-2.5 font-display uppercase tracking-wider text-brand-textMuted">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={`${row.type}-${row.id}`} className="border-t border-brand-border"><td className="px-3 py-2.5 text-brand-heading">{row.beneficiary}</td><td className="px-3 py-2.5 capitalize">{row.type}{row.kind?` · ${row.kind}`:''}</td><td className="px-3 py-2.5 font-mono">{row.order_number}</td><td className="px-3 py-2.5">{row.rate==null?'—':`${row.rate}%`}</td><td className="px-3 py-2.5 font-mono">${Number(row.amount).toFixed(2)}</td><td className="px-3 py-2.5 capitalize">{row.status}</td><td className="px-3 py-2.5">{new Date(row.created_at).toLocaleDateString()}</td><td className="px-3 py-2.5"><div className="flex gap-1">{row.status==='pending'&&<button disabled={busy===row.id} onClick={()=>void change(row,'approved')} className="btn-ghost">Approve</button>}{row.status==='approved'&&<button disabled={busy===row.id} onClick={()=>void change(row,'paid')} className="btn-primary">Mark paid</button>}{row.status!=='paid'&&row.status!=='void'&&<button disabled={busy===row.id} onClick={()=>void change(row,'void')} className="btn-ghost">Void</button>}</div></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-8 text-center text-brand-textMuted">No commissions yet.</p>}</div>
  </div>;
}
