'use client';
import React, { useCallback, useEffect, useState } from 'react';

type Row = { id:string; type:'affiliate'|'seller'; beneficiary:string; order_number:string; kind?:string; rate?:number; amount:number; status:string; created_at:string; reference?:string|null };
export default function CommissionsPanel({ authedFetch }:{ authedFetch:(path:string, init?:RequestInit)=>Promise<Response> }) {
  const [rows,setRows]=useState<Row[]>([]); const [totals,setTotals]=useState<any>({}); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const load=useCallback(async()=>{ setError(''); const res=await authedFetch('/api/admin/commissions/manage'); const p=await res.json().catch(()=>null); if(!res.ok){setError(p?.message??'Could not load commissions.');return;} setRows(p.data.rows);setTotals(p.data.totals); },[authedFetch]);
  useEffect(()=>{void load();},[load]);
  const change=async(row:Row,status:string)=>{ const reference=status==='paid' ? window.prompt('Payment reference (optional)') : ''; if(status==='paid'&&reference===null)return; setBusy(row.id); const res=await authedFetch('/api/admin/commissions/manage',{method:'PATCH',body:JSON.stringify({id:row.id,type:row.type,status,reference})}); const p=await res.json().catch(()=>null); if(!res.ok)setError(p?.message??'Could not update commission.'); else await load(); setBusy(''); };
  const actionsFor=(row:Row)=><>{row.status==='pending'&&<button disabled={busy===row.id} onClick={()=>void change(row,'approved')} className="btn-ghost">Approve</button>}{row.status==='approved'&&<button disabled={busy===row.id} onClick={()=>void change(row,'paid')} className="btn-primary">Mark paid</button>}{row.status!=='paid'&&row.status!=='void'&&<button disabled={busy===row.id} onClick={()=>void change(row,'void')} className="btn-ghost">Void</button>}</>;
  return <div className="space-y-4">
    <div className="grid grid-cols-2 gap-px border border-brand-border bg-brand-border md:grid-cols-4">{['pending','approved','paid','void'].map(s=><div key={s} className="bg-brand-card p-4"><div className="eyebrow">{s}</div><div className="mt-2 font-display text-xl font-black text-brand-heading">${Number(totals[s]??0).toFixed(2)}</div></div>)}</div>
    {error&&<div className="border border-brand-accent/50 bg-brand-card p-3 text-xs">{error}</div>}
    {/* Phones: one card per commission. */}
    <ul className="space-y-2 md:hidden">{rows.map(row=><li key={`${row.type}-${row.id}`} className="border border-brand-border bg-brand-card p-3 text-xs"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold text-brand-heading">{row.beneficiary}</p><p className="capitalize text-brand-textMuted">{row.type}{row.kind?` · ${row.kind}`:''} · <span className="font-mono normal-case">{row.order_number}</span></p></div><div className="flex-none text-right"><p className="font-mono text-sm text-brand-heading">${Number(row.amount).toFixed(2)}</p><p className="capitalize text-brand-textMuted">{row.status}{row.rate==null?'':` · ${row.rate}%`}</p></div></div><p className="mt-1 text-[0.6875rem] text-brand-textMuted">{new Date(row.created_at).toLocaleDateString()}</p>{row.status!=='paid'&&row.status!=='void'&&<div className="mt-2 flex flex-wrap gap-2 border-t border-brand-border/60 pt-2">{actionsFor(row)}</div>}</li>)}{rows.length===0&&<li className="border border-brand-border p-8 text-center text-brand-textMuted">No commissions yet.</li>}</ul>
    <div className="hidden overflow-x-auto border border-brand-border md:block"><table className="w-full min-w-[52rem] text-left text-xs"><thead className="bg-brand-card"><tr>{['Person','Source','Order','Rate','Amount','Status','Created','Actions'].map(h=><th key={h} className="px-3 py-2.5 font-display uppercase tracking-wider text-brand-textMuted">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={`${row.type}-${row.id}`} className="border-t border-brand-border"><td className="px-3 py-2.5 text-brand-heading">{row.beneficiary}</td><td className="px-3 py-2.5 capitalize">{row.type}{row.kind?` · ${row.kind}`:''}</td><td className="px-3 py-2.5 font-mono">{row.order_number}</td><td className="px-3 py-2.5">{row.rate==null?'—':`${row.rate}%`}</td><td className="px-3 py-2.5 font-mono">${Number(row.amount).toFixed(2)}</td><td className="px-3 py-2.5 capitalize">{row.status}</td><td className="px-3 py-2.5">{new Date(row.created_at).toLocaleDateString()}</td><td className="px-3 py-2.5"><div className="flex gap-1">{actionsFor(row)}</div></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-8 text-center text-brand-textMuted">No commissions yet.</p>}</div>
  </div>;
}
