-- USA Peptides - sales agents
--
-- Run in the Supabase SQL editor after 0006_users_fixes.sql. Safe to re-run.
--
-- How a sale becomes an agent's, in the order it is decided:
--
--   1. The customer came through the agent's referral link   -> referral_link
--   2. The customer has ordered before, and that earlier
--      order belongs to an active agent                        -> customer_history
--   3. Otherwise the order arrives unclaimed. An agent presses
--      "Claim this order"; the first to press it gets it     -> claim
--   4. A super admin can also hand an order to an agent       -> assigned
--
-- A customer belongs to whoever owns their orders. That is derived from the
-- orders, not stored on the customer, so the two can never disagree.
--
-- Ownership is always an admin_users id, never a name. A name match breaks the
-- day two people share one or somebody corrects a spelling.

-- ---------------------------------------------------------------------------
-- 1. The role
--
-- Kept separate from `tier`. Tier is the recruiting tree (staff -> sub-user);
-- role is what a team member does. A sales agent is tier 'staff', so they can
-- be the parent of sub-users exactly as staff already can.
-- ---------------------------------------------------------------------------

alter table public.admin_users add column if not exists role text not null default 'staff';

do $$ begin
  alter table public.admin_users add constraint admin_users_role_check
    check (role in ('staff', 'sales_agent'));
exception when duplicate_object then null; end $$;

-- A super admin sees everything, so "only their own" would mean nothing; a
-- sub-user already has its own closed screen. Refused here as well as in the
-- API, so a direct write cannot produce either.
do $$ begin
  alter table public.admin_users add constraint admin_users_sales_agent_shape
    check (role <> 'sales_agent' or (tier = 'staff' and not is_superadmin));
exception when duplicate_object then null; end $$;

-- Referral code for agents and sub-users. Generated by the API with
-- crypto.randomInt; compared case-insensitively like affiliate codes.
alter table public.admin_users add column if not exists referral_code text;

create unique index if not exists admin_users_referral_code_idx
  on public.admin_users (upper(referral_code))
  where referral_code is not null;

create index if not exists admin_users_role_idx on public.admin_users (role, status);

-- ---------------------------------------------------------------------------
-- 2. Orders: who is credited, and how
--
-- orders.referred_by already exists (0006), deliberately without a foreign key
-- so an order keeps its attribution after the person leaves.
-- ---------------------------------------------------------------------------

alter table public.orders add column if not exists agent_source     text;
alter table public.orders add column if not exists agent_claimed_at timestamptz;

do $$ begin
  alter table public.orders add constraint orders_agent_source_check
    check (agent_source is null or agent_source in ('referral_link', 'customer_history', 'claim', 'assigned'));
exception when duplicate_object then null; end $$;

create index if not exists orders_referred_by_idx on public.orders (referred_by, created_at desc);
create index if not exists orders_email_history_idx on public.orders (email, created_at) where referred_by is not null;

-- ---------------------------------------------------------------------------
-- 3. Leads: an owner, claimed the same way as orders
--
-- ON DELETE SET NULL: when an agent is removed their leads go back to
-- unclaimed rather than disappearing or blocking the delete.
-- ---------------------------------------------------------------------------

alter table public.leads
  add column if not exists owner_id uuid references public.admin_users (id) on delete set null;

create index if not exists leads_owner_idx on public.leads (owner_id, created_at desc);
