-- USA Peptides - sales agents
--
-- Run in the Supabase SQL editor after 0006_users_fixes.sql. Safe to re-run.
--
-- A sales agent is a team member who sees only their own leads, customers and
-- orders, has a referral code of their own, and earns a commission % set per
-- person (admin_users.commission_rate, which already exists).
--
-- Ownership is recorded as an admin_users id, never as a name. Matching on a
-- name breaks the day two people share one, or somebody corrects a spelling.

-- ---------------------------------------------------------------------------
-- 1. The role
--
-- Kept separate from `tier`. Tier is the recruiting tree (staff -> sub-user);
-- role is what a team member does. A sales agent is still tier 'staff'.
-- ---------------------------------------------------------------------------

alter table public.admin_users add column if not exists role text not null default 'staff';

do $$ begin
  alter table public.admin_users add constraint admin_users_role_check
    check (role in ('staff', 'sales_agent'));
exception when duplicate_object then null; end $$;

-- A super admin sees everything, so "only their own" would mean nothing; and a
-- sub-user already has its own closed screen. Both are refused here as well as
-- in the API, so a direct write cannot produce either.
do $$ begin
  alter table public.admin_users add constraint admin_users_sales_agent_shape
    check (role <> 'sales_agent' or (tier = 'staff' and not is_superadmin));
exception when duplicate_object then null; end $$;

-- The agent's own referral code. Generated by the API with crypto.randomInt,
-- compared case-insensitively like affiliate codes.
alter table public.admin_users add column if not exists referral_code text;

create unique index if not exists admin_users_referral_code_idx
  on public.admin_users (upper(referral_code))
  where referral_code is not null;

create index if not exists admin_users_role_idx on public.admin_users (role, status);

-- ---------------------------------------------------------------------------
-- 2. Ownership
--
-- ON DELETE SET NULL: when an agent is removed, their leads and customers
-- become unowned and visible to a super admin to hand to somebody else, rather
-- than disappearing or blocking the delete.
--
-- Orders already carry referred_by (0006), deliberately without a foreign key
-- so an order keeps its attribution after the person leaves.
-- ---------------------------------------------------------------------------

alter table public.leads
  add column if not exists owner_id uuid references public.admin_users (id) on delete set null;

alter table public.customer_profiles
  add column if not exists owner_id uuid references public.admin_users (id) on delete set null;

create index if not exists leads_owner_idx             on public.leads (owner_id, created_at desc);
create index if not exists customer_profiles_owner_idx on public.customer_profiles (owner_id, created_at desc);
create index if not exists orders_referred_by_idx      on public.orders (referred_by, created_at desc);
